"""Add escalation fields to incident

Revision ID: 09ecf55857b7
Revises: 
Create Date: 2024-09-29 15:12:54.684824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ecf55857b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Set a default value before making 'priority' NOT NULL
    op.execute("UPDATE incident SET priority = 'P4' WHERE priority IS NULL")

    op.add_column('incident', sa.Column('escalation_level', sa.String(length=50), nullable=True))
    op.add_column('incident', sa.Column('escalated_at', sa.DateTime(), nullable=True))
    op.add_column('incident', sa.Column('is_sla_breached', sa.Boolean(), nullable=True))
    op.add_column('incident', sa.Column('breached_at', sa.DateTime(), nullable=True))
    
    # Alter 'priority' to be non-nullable
    op.alter_column('incident', 'priority', existing_type=sa.VARCHAR(length=10), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('incident', 'breached_at')
    op.drop_column('incident', 'is_sla_breached')
    op.drop_column('incident', 'escalated_at')
    op.drop_column('incident', 'escalation_level')
    # ### end Alembic commands ###
